const menu = {
    list() {
        return [
    {
        "backMenu":[
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
    {
        "backMenu":[
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-cart",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"购物车",
                        "menuJump":"列表",
                        "tableName":"cart"
                    }
                ],
                "menu":"购物车"
            }
			,
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看",
                        ],
                        "menu":"公告",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告"
            }
			,
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看",
                        ],
                        "menu":"供应商信息",
                        "menuJump":"列表",
                        "tableName":"gongyingshang"
                    }
                ],
                "menu":"供应商信息"
            }
			,
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看",
                        ],
                        "menu":"会员",
                        "menuJump":"列表",
                        "tableName":"huiyuan"
                    }
                ],
                "menu":"会员"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-goods",
                        "buttons":[
                            "查看",
                        ],
                        "menu":"商品",
                        "menuJump":"列表",
                        "tableName":"shangpin"
                    }
                ],
                "menu":"商品"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-goods",
                        "buttons":[
                            "查看",
                        ],
                        "menu":"出入库",
                        "menuJump":"列表",
                        "tableName":"shangpinChuruInout"
                    }
                ],
                "menu":"出入库"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-goods",
                        "buttons":[
                            "查看",
                        ],
                        "menu":"出入库详情",
                        "menuJump":"列表",
                        "tableName":"shangpinChuruInoutList"
                    }
                ],
                "menu":"出入库详情"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-order",
                        "buttons":[
                            "查看",
                        ],
                        "menu":"商品订单",
                        "menuJump":"列表",
                        "tableName":"shangpinOrder"
                    }
                ],
                "menu":"商品订单"
            }
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"是",
        "hasFrontRegister":"是",
        "roleName":"用户",
        "tableName":"yonghu"
    }
]

	}
}
export default menu;
